name: Build and deploy Vite + React to Azure Web App - FreshdealBusinessWebsite

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Zip dist folder
        run: |
          cd dist
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./release

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: FreshdealBusinessWebsite
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_140706989B984EB1B4DA4F23CBF61FCB }}
          package: ./release/release.zip
